# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2564c0631ee9bb2014a9b086e91dc89c982abcf52b55f79857493d453783a1ed4d6cffaedcd2f50d94470944fefecad2e8de8ba27ef1c7c7f9a7fa997b7ae931

test:
  secret_key_base: 6c93862cb73a0ccbfa5a4c82adb0ba77ab20bcba40b83015d9246e6319d5ff9f6008aee901ead8e7e8e017fea04d83932f01f9cb0f9833ba90453d9523fa4557

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
