#!/bin/bash
git --work-tree=/var/www/facturacohete-front-end/wwwroot --git-dir=/home/safe/facturacohete-front-end checkout -f
cd /var/www/facturacohete-front-end/wwwroot/project/website/
bundle install
RAILS_ENV=production bundle exec rake assets:precompile
sudo /var/www/facturacohete-front-end/wwwroot/conf/git/restart-app
echo "Develop ref received.  Deploying develop branch to production..."
